# Generated by Django 5.1 on 2024-09-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_delete_volunteeropportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
